# Generated by Django 5.1.12 on 2025-09-06 23:45

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255, validators=[utils.validators.name_no_digits_validator])),
                ('bank_name', models.CharField(max_length=255, validators=[utils.validators.non_empty_text_validator])),
                ('account_number', models.CharField(max_length=50, validators=[utils.validators.bank_account_validator])),
                ('account_type', models.CharField(choices=[('SAVINGS', 'Savings Account'), ('CURRENT', 'Current Account'), ('BUSINESS', 'Business Account'), ('OVERDRAFT', 'Overdraft Account'), ('JOINT', 'Joint Account')], default='SAVINGS', max_length=20)),
                ('ifsc_code', models.CharField(help_text='Indian Financial System Code', max_length=11, validators=[utils.validators.ifsc_validator])),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_address', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_city', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_state', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_pincode', models.CharField(blank=True, max_length=6, null=True, validators=[utils.validators.pincode_validator])),
            ],
            options={
                'verbose_name': 'Banking Detail',
                'verbose_name_plural': 'Banking Details',
                'db_table': 'banking_detail',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='PostalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(unique=True)),
                ('officename', models.CharField(blank=True, max_length=255, null=True)),
                ('officeType', models.CharField(blank=True, max_length=50, null=True)),
                ('Deliverystatus', models.CharField(blank=True, max_length=50, null=True)),
                ('divisionname', models.CharField(blank=True, max_length=100, null=True)),
                ('regionname', models.CharField(blank=True, max_length=100, null=True)),
                ('circlename', models.CharField(blank=True, max_length=100, null=True)),
                ('Taluk', models.CharField(blank=True, max_length=100, null=True)),
                ('Districtname', models.CharField(blank=True, max_length=100, null=True)),
                ('statename', models.CharField(blank=True, max_length=100, null=True)),
                ('Telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('relatedSuboffice', models.CharField(blank=True, max_length=100, null=True)),
                ('relatedHeadoffice', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('via', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('STATE_CHOICES', 'STATE_CHOICES'), ('GENDER', 'GENDER'), ('TITLE_CHOICES', 'TITLE_CHOICES'), ('BRAND_TYPE', 'BRAND_TYPE'), ('MODEL_TYPE', 'MODEL_TYPE'), ('WHEELS_TYPE', 'WHEELS_TYPE'), ('FUEL_TYPE', 'FUEL_TYPE'), ('EXPENSE_TYPES', 'EXPENSE_TYPES'), ('STATUS_CHOICES', 'STATUS_CHOICES'), ('FREIGHT_MODE', 'FREIGHT_MODE'), ('TRANSACTION_TYPES', 'TRANSACTION_TYPES'), ('EXPENSE_CATEGORIES', 'EXPENSE_CATEGORIES'), ('MODE_OF_PAYMENT', 'MODE_OF_PAYMENT'), ('PACKAGING_TYPES', 'PACKAGING_TYPES'), ('LOCATION_TYPES', 'LOCATION_TYPES'), ('TRUCK_TYPE', 'TRUCK_TYPE'), ('ENGINE_TYPE', 'ENGINE_TYPE'), ('BODY_TYPE', 'BODY_TYPE'), ('BROKER_VEHICLE_TYPE', 'BROKER_VEHICLE_TYPE'), ('MATERIAL_TYPE', 'MATERIAL_TYPE'), ('WEIGHT_UNITS', 'WEIGHT_UNITS'), ('SHIPMENT_DOC_TYPE', 'SHIPMENT_DOC_TYPE'), ('CAPACITY_TONS', 'CAPACITY_TONS')], max_length=100, null=True)),
                ('internal_value', models.CharField(max_length=100)),
                ('display_value', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('category', 'internal_value')},
            },
        ),
    ]
