# Generated by Django 5.1.12 on 2025-11-04 21:26

from django.db import migrations, models


CHOICE_FIELD_CHOICES = [
    ('LOCATION_STATE', 'Location State'),
    ('PERSON_GENDER', 'Person Gender'),
    ('PERSON_TITLE', 'Person Title'),
    ('VEHICLE_BRAND', 'Vehicle Brand'),
    ('VEHICLE_MODEL', 'Vehicle Model'),
    ('VEHICLE_WHEEL_CONFIGURATION', 'Vehicle Wheel Configuration'),
    ('VEHICLE_FUEL_TYPE', 'Vehicle Fuel Type'),
    ('VEHICLE_TRUCK_TYPE', 'Vehicle Truck Type'),
    ('VEHICLE_ENGINE_TYPE', 'Vehicle Engine Type'),
    ('VEHICLE_BODY_TYPE', 'Vehicle Body Type'),
    ('VEHICLE_CAPACITY_TONNAGE', 'Vehicle Capacity (Tonnage)'),
    ('VEHICLE_SPECIFICATION', 'Vehicle Specification'),
    ('VEHICLE_DOCUMENT_TYPE', 'Vehicle Document Type'),
    ('DRIVER_DOCUMENT_TYPE', 'Driver Document Type'),
    ('ORGANIZATION_DOCUMENT_TYPE', 'Organization Document Type'),
    ('ORGANIZATION_TYPE', 'Organization Type'),
    ('BROKER_VEHICLE_TYPE', 'Broker Vehicle Type'),
    ('LOCATION_TYPE', 'Location Type'),
    ('SHIPMENT_FREIGHT_MODE', 'Shipment Freight Mode'),
    ('SHIPMENT_PACKAGING_TYPE', 'Shipment Packaging Type'),
    ('SHIPMENT_MATERIAL_TYPE', 'Shipment Material Type'),
    ('SHIPMENT_DOCUMENT_TYPE', 'Shipment Document Type'),
    ('WEIGHT_UNIT', 'Weight Unit'),
    ('FINANCE_EXPENSE_TYPE', 'Finance Expense Type'),
    ('FINANCE_EXPENSE_CATEGORY', 'Finance Expense Category'),
    ('FINANCE_TRANSACTION_TYPE', 'Finance Transaction Type'),
    ('FINANCE_PAYMENT_MODE', 'Finance Payment Mode'),
    ('BANK_ACCOUNT_TYPE', 'Bank Account Type'),
    ('GENERAL_STATUS', 'General Status'),
    ('MAINTENANCE_SERVICE_TYPE', 'Maintenance Service Type'),
    ('MAINTENANCE_ITEM', 'Maintenance Item'),
    ('MAINTENANCE_VENDOR', 'Maintenance Vendor'),
    ('MAINTENANCE_TRANSACTION_TYPE', 'Maintenance Transaction Type'),
    ('TYRE_BRAND', 'Tyre Brand'),
    ('TYRE_MODEL', 'Tyre Model'),
    ('TYRE_SIZE', 'Tyre Size'),
    ('TYRE_TYPE', 'Tyre Type'),
    ('TYRE_TUBE_TYPE', 'Tyre Tube Type'),
    ('TYRE_PURCHASE_TYPE', 'Tyre Purchase Type'),
    ('TYRE_POSITION', 'Tyre Position'),
]


CATEGORY_RENAMES = {
    'STATE_CHOICES': 'LOCATION_STATE',
    'GENDER': 'PERSON_GENDER',
    'TITLE_CHOICES': 'PERSON_TITLE',
    'BRAND_TYPE': 'VEHICLE_BRAND',
    'MODEL_TYPE': 'VEHICLE_MODEL',
    'WHEELS_TYPE': 'VEHICLE_WHEEL_CONFIGURATION',
    'FUEL_TYPE': 'VEHICLE_FUEL_TYPE',
    'EXPENSE_TYPES': 'FINANCE_EXPENSE_TYPE',
    'STATUS_CHOICES': 'GENERAL_STATUS',
    'FREIGHT_MODE': 'SHIPMENT_FREIGHT_MODE',
    'TRANSACTION_TYPES': 'FINANCE_TRANSACTION_TYPE',
    'EXPENSE_CATEGORIES': 'FINANCE_EXPENSE_CATEGORY',
    'MODE_OF_PAYMENT': 'FINANCE_PAYMENT_MODE',
    'PACKAGING_TYPES': 'SHIPMENT_PACKAGING_TYPE',
    'LOCATION_TYPES': 'LOCATION_TYPE',
    'TRUCK_TYPE': 'VEHICLE_TRUCK_TYPE',
    'ENGINE_TYPE': 'VEHICLE_ENGINE_TYPE',
    'BODY_TYPE': 'VEHICLE_BODY_TYPE',
    'MATERIAL_TYPE': 'SHIPMENT_MATERIAL_TYPE',
    'WEIGHT_UNITS': 'WEIGHT_UNIT',
    'SHIPMENT_DOC_TYPE': 'SHIPMENT_DOCUMENT_TYPE',
    'CAPACITY_TONS': 'VEHICLE_CAPACITY_TONNAGE',
    'TRUCK_SPECIFICATION': 'VEHICLE_SPECIFICATION',
}


def rename_choice_categories(apps, schema_editor):
    Choice = apps.get_model('configuration', 'Choice')
    for old, new in CATEGORY_RENAMES.items():
        Choice.objects.filter(category=old).update(category=new)


def bootstrap_choice_values(apps, schema_editor):
    Choice = apps.get_model('configuration', 'Choice')

    definitions = {
        'DRIVER_DOCUMENT_TYPE': [
            ('LICENSE', 'Driving License'),
            ('AADHAAR', 'Aadhaar'),
            ('PAN', 'PAN'),
            ('MEDICAL', 'Medical/Health'),
            ('POLICE', 'Police Verification'),
            ('OTHER', 'Other'),
        ],
        'VEHICLE_DOCUMENT_TYPE': [
            ('REG_CERT', 'Registration Certificate'),
            ('TAX', 'Tax'),
            ('NATIONAL_PERMIT', 'National Permit'),
            ('STATE_PERMIT', 'State Permit'),
            ('POLLUTION', 'Pollution'),
            ('INSURANCE', 'Insurance'),
            ('VLTD_CERT', 'VLTD Certificate'),
            ('SPEED_GOVERNOR', 'Speed Governor Certificate'),
        ],
        'ORGANIZATION_DOCUMENT_TYPE': [
            ('PAN', 'PAN Card'),
            ('TDS_DECLARATION', 'TDS Declaration'),
            ('GST_CERTIFICATE', 'GST Certificate'),
            ('CANCELLED_CHEQUE', 'Cancelled Cheque'),
        ],
        'ORGANIZATION_TYPE': [
            ('BROKER', 'Broker'),
            ('TRANSPORTER', 'Transporter'),
            ('CONSIGNOR-AND-CONSIGNEE', 'Consignor & Consignee'),
            ('OWNER', 'Owner'),
        ],
        'BANK_ACCOUNT_TYPE': [
            ('SAVINGS', 'Savings Account'),
            ('CURRENT', 'Current Account'),
            ('BUSINESS', 'Business Account'),
            ('OVERDRAFT', 'Overdraft Account'),
            ('JOINT', 'Joint Account'),
        ],
        'MAINTENANCE_TRANSACTION_TYPE': [
            ('Install', 'Install'),
            ('Replace', 'Replace'),
            ('Rotate', 'Rotate'),
            ('Remove', 'Remove'),
            ('Service', 'Service'),
        ],
    }

    for category, values in definitions.items():
        for internal_value, display_value in values:
            choice, created = Choice.objects.get_or_create(
                category=category,
                internal_value=internal_value,
                defaults={'display_value': display_value},
            )
            if not created and choice.display_value != display_value:
                choice.display_value = display_value
                choice.save(update_fields=['display_value'])


def remove_bootstrapped_choices(apps, schema_editor):
    Choice = apps.get_model('configuration', 'Choice')
    categories = {
        'DRIVER_DOCUMENT_TYPE': ['LICENSE', 'AADHAAR', 'PAN', 'MEDICAL', 'POLICE', 'OTHER'],
        'VEHICLE_DOCUMENT_TYPE': ['REG_CERT', 'TAX', 'NATIONAL_PERMIT', 'STATE_PERMIT', 'POLLUTION', 'INSURANCE', 'VLTD_CERT', 'SPEED_GOVERNOR'],
        'ORGANIZATION_DOCUMENT_TYPE': ['PAN', 'TDS_DECLARATION', 'GST_CERTIFICATE', 'CANCELLED_CHEQUE'],
        'ORGANIZATION_TYPE': ['BROKER', 'TRANSPORTER', 'CONSIGNOR-AND-CONSIGNEE', 'OWNER'],
        'BANK_ACCOUNT_TYPE': ['SAVINGS', 'CURRENT', 'BUSINESS', 'OVERDRAFT', 'JOINT'],
        'MAINTENANCE_TRANSACTION_TYPE': ['Install', 'Replace', 'Rotate', 'Remove', 'Service'],
    }

    for category, internal_values in categories.items():
        Choice.objects.filter(category=category, internal_value__in=internal_values).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_alter_choice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='category',
            field=models.CharField(
                blank=True,
                choices=CHOICE_FIELD_CHOICES,
                max_length=100,
                null=True,
                help_text='Logical grouping for this choice (see configuration.constants.ChoiceCategory)',
            ),
        ),
        migrations.RunPython(rename_choice_categories, migrations.RunPython.noop),
        migrations.RunPython(bootstrap_choice_values, remove_bootstrapped_choices),
    ]
