# Generated by Django 5.1.12 on 2025-09-06 23:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('entity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workflow_type', models.CharField(choices=[('EXPENSE_APPROVAL', 'Expense Approval'), ('ADVANCE_APPROVAL', 'Advance Approval'), ('INVOICE_APPROVAL', 'Invoice Approval')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_approval_workflow',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VIEW_OWN_EXPENSES', 'View Own Expenses'), ('ADD_OWN_EXPENSES', 'Add Own Expenses'), ('VIEW_OWN_ADVANCES', 'View Own Advances'), ('REQUEST_ADVANCE', 'Request Advance'), ('VIEW_OWN_SHIPMENTS', 'View Own Shipments'), ('VIEW_OWN_BALANCE', 'View Own Balance'), ('VIEW_SHIPMENT_DETAILS', 'View Shipment Details'), ('VIEW_TRANSPORTER_SHIPMENTS', 'View Transporter Shipments'), ('VIEW_COMPANY_SHIPMENTS', 'View Company Shipments'), ('VIEW_BROKER_SHIPMENTS', 'View Broker Shipments'), ('VIEW_OWNER_VEHICLES', 'View Owner Vehicles'), ('VIEW_OWNER_SHIPMENTS', 'View Owner Shipments'), ('VIEW_OWNER_EXPENSES', 'View Owner Expenses'), ('ADD_EXPENSE', 'Add Expense'), ('ADD_CONSIGNMENT', 'Add Consignment'), ('EDIT_OPERATION_DETAILS', 'Edit Operation Details'), ('APPROVE_DRIVER_EXPENSES', 'Approve Driver Expenses'), ('APPROVE_DRIVER_ADVANCES', 'Approve Driver Advances'), ('VIEW_FINANCIAL_DETAILS', 'View Financial Details'), ('APPROVE_FINANCIAL_TRANSACTIONS', 'Approve Financial Transactions'), ('MANAGE_INVOICES', 'Manage Invoices'), ('MANAGE_PAYMENTS', 'Manage Payments'), ('ALL_ACCESS', 'All Access'), ('CREATE_ENTITIES', 'Create All Entities'), ('MANAGE_USERS', 'Manage Users'), ('MANAGE_ROLES', 'Manage Roles')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DRIVER', 'Driver'), ('TRANSPORTER', 'Transporter'), ('COMPANY', 'Company'), ('BROKER', 'Broker'), ('OWNER', 'Owner'), ('OPERATION', 'Operation'), ('FINANCE', 'Finance'), ('SUPERUSER', 'Superuser')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_role',
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('is_required', models.BooleanField(default=True)),
                ('can_override', models.BooleanField(default=False, help_text='Can this step be overridden by higher authority?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='users.approvalworkflow')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='users.role')),
            ],
            options={
                'db_table': 'users_approval_step',
                'ordering': ['workflow', 'step_order'],
                'unique_together': {('workflow', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('account_locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_password_change', models.DateTimeField(auto_now_add=True)),
                ('password_expires_at', models.DateTimeField(blank=True, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_secret', models.CharField(blank=True, max_length=32)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='security_user_set', related_query_name='security_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='security_user_set', related_query_name='security_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_custom_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_approval_requests', to='users.approvalstep')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='users.approvalworkflow')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='users.customuser')),
            ],
            options={
                'db_table': 'users_approval_request',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField()),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'login_attempt',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['username', 'timestamp'], name='login_attem_usernam_940c93_idx'), models.Index(fields=['ip_address', 'timestamp'], name='login_attem_ip_addr_c30e68_idx'), models.Index(fields=['success', 'timestamp'], name='login_attem_success_5a066b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RateLimitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100)),
                ('identifier_type', models.CharField(choices=[('IP', 'IP'), ('USER', 'User')], max_length=10)),
                ('endpoint', models.CharField(max_length=200)),
                ('request_count', models.PositiveIntegerField(default=1)),
                ('window_start', models.DateTimeField(auto_now_add=True)),
                ('last_request', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rate_limit_tracker',
                'indexes': [models.Index(fields=['identifier', 'window_start'], name='rate_limit__identif_1c9b10_idx'), models.Index(fields=['endpoint', 'window_start'], name='rate_limit__endpoin_ce177c_idx')],
                'unique_together': {('identifier', 'identifier_type', 'endpoint')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.role')),
            ],
            options={
                'db_table': 'users_role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions assigned to this role', related_name='roles', through='users.RolePermission', to='users.permission'),
        ),
        migrations.CreateModel(
            name='SecurityConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_configuration',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, help_text='Driver this role applies to', null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.driver')),
                ('entity', models.ForeignKey(blank=True, help_text='Organization this role applies to', null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.customuser')),
            ],
            options={
                'db_table': 'users_user_role',
                'unique_together': {('user', 'role', 'entity', 'driver')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles assigned to this user', related_name='users', through='users.UserRole', to='users.role'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('APPROVE', 'Approve'), ('REJECT', 'Reject')], max_length=10)),
                ('content_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('object_repr', models.CharField(max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('additional_info', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_log_user_id_835db7_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_log_content_21fd81_idx'), models.Index(fields=['action', 'timestamp'], name='audit_log_action_09d227_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('CANCEL', 'Cancel'), ('OVERRIDE', 'Override')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='users.approvalrequest')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to='users.approvalstep')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to='users.customuser')),
            ],
            options={
                'db_table': 'users_approval_action',
                'unique_together': {('approval_request', 'step')},
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Successful Login'), ('LOGIN_FAILED', 'Failed Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('PERMISSION_DENIED', 'Permission Denied'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('DATA_ACCESS', 'Data Access'), ('DATA_MODIFICATION', 'Data Modification'), ('SECURITY_VIOLATION', 'Security Violation'), ('RATE_LIMIT_EXCEEDED', 'Rate Limit Exceeded'), ('INVALID_TOKEN', 'Invalid Token'), ('SESSION_TIMEOUT', 'Session Timeout'), ('TWO_FACTOR_AUTH', 'Two-Factor Authentication')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_event',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='security_ev_user_id_d0f1bf_idx'), models.Index(fields=['event_type', 'timestamp'], name='security_ev_event_t_0b896c_idx'), models.Index(fields=['severity', 'timestamp'], name='security_ev_severit_070cf6_idx'), models.Index(fields=['ip_address'], name='security_ev_ip_addr_a11438_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('READ', 'Read Only'), ('WRITE', 'Read/Write'), ('ADMIN', 'Admin')], default='READ', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for this permission', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this permission')),
                ('granted_by', models.ForeignKey(blank=True, help_text='User who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to='users.customuser')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='entity.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_permissions', to='users.customuser')),
            ],
            options={
                'db_table': 'security_tenant_permission',
                'indexes': [models.Index(fields=['user', 'tenant'], name='security_te_user_id_0624c5_idx'), models.Index(fields=['tenant', 'is_active'], name='security_te_tenant__0fe622_idx'), models.Index(fields=['expires_at'], name='security_te_expires_89ce65_idx')],
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
