# Generated by Django 5.1.12 on 2025-11-02 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('DRIVER', 'Driver'), ('TRANSPORTER', 'Transporter'), ('CONSIGNOR-AND-CONSIGNEE', 'Company'), ('BROKER', 'Broker'), ('OWNER', 'Owner'), ('OPERATION', 'Operation'), ('FINANCE', 'Finance'), ('SUPERUSER', 'Superuser')], max_length=40, unique=True),
        ),
    ]
