# Generated by Django 5.1.12 on 2025-09-06 23:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('invoice_ref', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('issue_date', models.DateField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_freight', models.DecimalField(decimal_places=2, default=0, help_text='Consignment total freight amount', max_digits=15)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, help_text='Total driver/owner expenses', max_digits=15)),
                ('total_advance', models.DecimalField(decimal_places=2, default=0, help_text='Total advances (shipment + driver advances)', max_digits=15)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, help_text='Balance after total freight and expenses', max_digits=15)),
                ('payment_received', models.DecimalField(decimal_places=2, default=0, help_text='Total payments received', max_digits=15)),
                ('total_dues', models.DecimalField(decimal_places=2, default=0, help_text='Remaining dues after all deductions', max_digits=15)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Invoice notes and remarks', null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='OtherExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('paid_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'other_expense',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('IMPS', 'IMPS'), ('NEFT', 'NEFT'), ('RTGS', 'RTGS'), ('MOBILE_BANKING', 'Mobile Banking'), ('NET_BANKING', 'Net Banking'), ('WALLET', 'Digital Wallet'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card')], default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, help_text='Bank transaction reference', max_length=100, null=True)),
                ('utr_number', models.CharField(blank=True, help_text='Unique Transaction Reference', max_length=22, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Bank transaction ID', max_length=100, null=True)),
                ('processed_datetime', models.DateTimeField(blank=True, null=True)),
                ('bank_charges', models.DecimalField(decimal_places=2, default=0, help_text='Bank charges for payment', max_digits=8)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
                ('cheque_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('cheque_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque_status', models.CharField(blank=True, choices=[('ISSUED', 'Issued'), ('DEPOSITED', 'Deposited'), ('CLEARED', 'Cleared'), ('BOUNCED', 'Bounced'), ('CANCELLED', 'Cancelled')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Payment notes and remarks', null=True)),
            ],
            options={
                'db_table': 'payment',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('advance', 'Advance'), ('revenue', 'Revenue'), ('refund', 'Refund')], default='expense', max_length=20)),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('tyre', 'Tyre'), ('fuel', 'Fuel'), ('driver', 'Driver'), ('shipment', 'Shipment'), ('office', 'Office'), ('insurance', 'Insurance'), ('permit', 'Permit & License'), ('toll', 'Toll & Charges'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('reference_number', models.CharField(blank=True, help_text='Invoice no, receipt no, etc.', max_length=100, null=True)),
                ('created_by', models.CharField(blank=True, help_text='Username or staff ID', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transaction',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('ADVANCE_PAYMENT', 'Advance Payment'), ('SALARY_PAYMENT', 'Salary Payment'), ('EXPENSE_REIMBURSEMENT', 'Expense Reimbursement'), ('VENDOR_PAYMENT', 'Vendor Payment'), ('REFUND', 'Refund'), ('INTERNAL_TRANSFER', 'Internal Transfer'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('OTHER', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transfer amount', max_digits=15)),
                ('bank_charges', models.DecimalField(decimal_places=2, default=0, help_text='Bank charges for transfer', max_digits=8)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Net amount after charges', max_digits=15)),
                ('transfer_mode', models.CharField(choices=[('IMPS', 'IMPS - Immediate Payment Service'), ('NEFT', 'NEFT - National Electronic Funds Transfer'), ('RTGS', 'RTGS - Real Time Gross Settlement'), ('UPI', 'UPI - Unified Payments Interface'), ('NET_BANKING', 'Net Banking'), ('MOBILE_BANKING', 'Mobile Banking'), ('API_TRANSFER', 'API Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], default='INITIATED', max_length=20)),
                ('transaction_id', models.CharField(help_text='Unique transaction identifier', max_length=100, unique=True)),
                ('utr_number', models.CharField(blank=True, help_text='UTR number from bank', max_length=22, null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Bank reference number', max_length=100, null=True)),
                ('initiated_datetime', models.DateTimeField(auto_now_add=True)),
                ('processed_datetime', models.DateTimeField(blank=True, null=True)),
                ('completed_datetime', models.DateTimeField(blank=True, null=True)),
                ('beneficiary_name', models.CharField(help_text='Beneficiary account holder name', max_length=255)),
                ('beneficiary_account_number', models.CharField(help_text='Beneficiary account number', max_length=50)),
                ('beneficiary_ifsc', models.CharField(help_text='Beneficiary IFSC code', max_length=11)),
                ('purpose_code', models.CharField(blank=True, help_text='Banking purpose code', max_length=10, null=True)),
                ('description', models.TextField(help_text='Transfer description and purpose')),
                ('notes', models.TextField(blank=True, help_text='Internal notes', null=True)),
                ('api_request_id', models.CharField(blank=True, help_text='API request identifier', max_length=100, null=True)),
                ('api_response_data', models.JSONField(blank=True, help_text='API response data', null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_banking_detail', models.ForeignKey(help_text='Source banking account', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_sent', to='configuration.bankingdetail')),
                ('related_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transfers', to='entity.driver')),
            ],
            options={
                'db_table': 'bank_transfer',
                'ordering': ['-initiated_datetime'],
            },
        ),
    ]
