# Generated by Django 5.1.12 on 2025-09-06 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('entity', '0001_initial'),
        ('financial', '0001_initial'),
        ('maintenance', '0001_initial'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransfer',
            name='related_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transfers', to='operations.shipment'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='to_banking_detail',
            field=models.ForeignKey(help_text='Destination banking account', on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to='configuration.bankingdetail'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='consignmentGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='operations.consignmentgroup'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='operations.shipment'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='related_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transfers', to='financial.invoice'),
        ),
        migrations.AddField(
            model_name='otherexpense',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'EXPENSE_CATEGORIES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_expense_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='otherexpense',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_expense_driver', to='entity.driver'),
        ),
        migrations.AddField(
            model_name='payment',
            name='from_banking_detail',
            field=models.ForeignKey(blank=True, help_text='Source banking account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_from', to='configuration.bankingdetail'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'MODE_OF_PAYMENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_mode_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='to_banking_detail',
            field=models.ForeignKey(blank=True, help_text='Destination banking account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_to', to='configuration.bankingdetail'),
        ),
        migrations.AddField(
            model_name='banktransfer',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transfers', to='financial.payment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='entity.driver'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_driver_advance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='operations.driveradvance'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_maintenance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='maintenance.maintenancerecord'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_other_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financial.otherexpense'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financial.payment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_shipment_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='operations.shipmentexpense'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_tyre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='maintenance.tyre'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_tyre_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='maintenance.tyretransaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='operations.shipment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='entity.vehicle'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['shipment'], name='invoice_shipmen_85d0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='invoice_issue_d_7c8de8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_paid'], name='invoice_is_paid_67168b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['shipment', 'status'], name='invoice_shipmen_9bd1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'issue_date'], name='invoice_status_308cd8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['consignmentGroup', 'status'], name='invoice_consign_d3881d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payment_payment_904250_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_status_1c1ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='payment_invoice_6a55b6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'status'], name='payment_invoice_f44c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date', 'status'], name='payment_payment_c8d4d0_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method', 'status'], name='payment_payment_cb4c74_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['transaction_id'], name='bank_transf_transac_ee1b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['utr_number'], name='bank_transf_utr_num_60270e_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['status'], name='bank_transf_status_68d43d_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['initiated_datetime'], name='bank_transf_initiat_7154e2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='transaction_transac_1d5fa8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='transaction_transac_d14223_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='transaction_categor_ffe30b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['shipment'], name='transaction_shipmen_8af931_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['driver'], name='transaction_driver__513afe_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['vehicle'], name='transaction_vehicle_5002ec_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['reference_number'], name='transaction_referen_825f84_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_by'], name='transaction_created_785e11_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'category'], name='transaction_transac_06a0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date', 'category'], name='transaction_transac_e078be_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['driver', 'transaction_date'], name='transaction_driver__f133dc_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['vehicle', 'transaction_date'], name='transaction_vehicle_106955_idx'),
        ),
    ]
