# Generated by Django 5.1.12 on 2025-11-02 01:41

import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_choice_category'),
        ('entity', '0002_initial'),
        ('financial', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('paid_by', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_document', models.FileField(blank=True, help_text='Purchase invoice document', null=True, upload_to=utils.validators.user_document_upload_path, validators=[utils.validators.document_file_validator])),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'category': 'EXPENSE_CATEGORIES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_expense_set', to='configuration.choice')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_expense_driver', to='entity.driver')),
            ],
            options={
                'db_table': 'office_expense',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='related_other_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financial.officeexpense'),
        ),
        migrations.DeleteModel(
            name='OtherExpense',
        ),
    ]
