# Generated by Django 5.1.12 on 2025-12-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_update_choice_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeexpense',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
