# Generated by Django 5.1.12 on 2026-04-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_alter_officeexpense_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='detention_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Detention charges applicable for this invoice', max_digits=12),
        ),
    ]
