# Generated by Django 5.1.12 on 2026-04-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_invoice_detention_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bill_to',
            field=models.CharField(choices=[('CONSIGNOR', 'Consignor'), ('CONSIGNEE', 'Consignee'), ('TRANSPORTER', 'Transporter'), ('BROKER', 'Broker')], default='CONSIGNOR', help_text='Select who this invoice is billed to', max_length=20),
        ),
    ]
