# Generated by Django 5.1.12 on 2025-09-06 23:45

import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TyreNo', models.CharField(blank=True, help_text='Unique tyre identification number', max_length=50)),
                ('Tyre_document', models.FileField(blank=True, help_text='Tyre warranty/documentation', null=True, upload_to=utils.validators.user_document_upload_path, validators=[utils.validators.document_file_validator])),
                ('Brand', models.CharField(blank=True, help_text='Tyre brand (e.g., MRF, CEAT, JK Tyre)', max_length=100, validators=[utils.validators.name_no_digits_validator])),
                ('Model', models.CharField(blank=True, help_text='Tyre model name', max_length=100)),
                ('Size', models.CharField(blank=True, help_text='Tyre size (e.g., 295/90R20)', max_length=20)),
                ('Type', models.CharField(blank=True, choices=[('Radial', 'Radial.'), ('Nylon', 'Nylon.'), ('Mx', 'Mx.')], help_text='Radial or Bias', max_length=50)),
                ('tube_type', models.CharField(blank=True, help_text='Tubeless or Tube-type', max_length=50, null=True)),
                ('position', models.CharField(blank=True, help_text='Front, Rear, All-position', max_length=50, null=True)),
                ('ply_rating', models.CharField(blank=True, help_text='Ply rating (e.g., 16PR, 18PR)', max_length=10, null=True)),
                ('Purchase_Date', models.DateField(blank=True, help_text='Date of tyre purchase')),
                ('Purchase_Type', models.CharField(blank=True, choices=[('Original', 'Original'), ('Used', 'Used'), ('Retread', 'Retread')], help_text='New, Used, or Retread', max_length=50)),
                ('Purchase_by', models.CharField(blank=True, help_text='Purchased by (person/organization)', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase amount', max_digits=10)),
                ('invoice_document', models.FileField(blank=True, help_text='Purchase invoice document', null=True, upload_to=utils.validators.user_document_upload_path, validators=[utils.validators.document_file_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_choice', models.ForeignKey(blank=True, help_text='Tyre brand from predefined choices', limit_choices_to={'category': 'TYRE_BRAND'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyre_brand_choice_set', to='configuration.choice')),
                ('position_choice', models.ForeignKey(blank=True, help_text='Tyre position from predefined choices', limit_choices_to={'category': 'TYRE_POSITION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyre_position_choice_set', to='configuration.choice')),
                ('tube_type_choice', models.ForeignKey(blank=True, help_text='Tube type from predefined choices', limit_choices_to={'category': 'TUBE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tube_type_choice_set', to='configuration.choice')),
                ('tyre_type_choice', models.ForeignKey(blank=True, help_text='Tyre type from predefined choices', limit_choices_to={'category': 'TYRE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyre_type_choice_set', to='configuration.choice')),
            ],
            options={
                'db_table': 'tyre',
                'ordering': ['Brand', 'Model', 'Size'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(blank=True, choices=[('Oil_Change', 'Oil_Change.'), ('Brake_Inspection', 'Brake_Inspection.'), ('Engine', 'Engine'), ('Tyre', 'Tyre')], max_length=100)),
                ('service_date', models.DateField(blank=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('mileage_at_service', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('performed_by', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='entity.vehicle')),
                ('tyre', models.ForeignKey(blank=True, help_text="Select tyre only when service type is 'Tyre'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.tyre')),
            ],
        ),
        migrations.CreateModel(
            name='TyreTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('FL', 'Front Left'), ('FR', 'Front Right'), ('RL', 'Rear Left'), ('RR', 'Rear Right'), ('SP', 'Spare')], max_length=2)),
                ('transaction_type', models.CharField(blank=True, choices=[('Install', 'Install'), ('Replace', 'Replace'), ('Rotate', 'Rotate'), ('Remove', 'Remove'), ('Service', 'Service')], max_length=20)),
                ('transaction_date', models.DateField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of tyre service/repair', max_digits=10, null=True)),
                ('performed_by', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tyre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='maintenance.tyre')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyre_transactions', to='entity.vehicle')),
            ],
        ),
        migrations.AddIndex(
            model_name='tyre',
            index=models.Index(fields=['Brand', 'Model'], name='tyre_Brand_ff2f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='tyre',
            index=models.Index(fields=['Size'], name='tyre_Size_7ba51b_idx'),
        ),
        migrations.AddIndex(
            model_name='tyre',
            index=models.Index(fields=['position'], name='tyre_positio_d5bd16_idx'),
        ),
        migrations.AddIndex(
            model_name='tyre',
            index=models.Index(fields=['Purchase_Date'], name='tyre_Purchas_a3ec96_idx'),
        ),
    ]
