# Generated by Django 5.1.12 on 2025-11-01 21:43

import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_choice_category'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerecord',
            old_name='cost',
            new_name='gst',
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='performed_by',
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label': 'entity', 'model__in': ['driver', 'owner']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='items',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'maintenance_item'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_item', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='maintenance_document',
            field=models.FileField(blank=True, null=True, upload_to=utils.validators.user_document_upload_path, validators=[utils.validators.document_file_validator]),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='next_mileage_due_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='vendors',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'maintenance_vendor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_vendor', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='service_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'maintenance_service_type'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_service_type', to='configuration.choice'),
        ),
    ]
