# Generated by Django 5.1.12 on 2025-11-01 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_rename_cost_maintenancerecord_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='service_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='tyre',
            field=models.ForeignKey(blank=True, help_text="Select tyre only when service type category is 'Tyre'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.tyre'),
        ),
    ]
