# Generated by Django 5.1.12 on 2025-11-01 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_choice_category'),
        ('maintenance', '0003_alter_maintenancerecord_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='items',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'MAINTENANCE_ITEM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_item', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='service_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'MAINTENANCE_SERVICE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_service_type', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='vendors',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'MAINTENANCE_VENDOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_vendor', to='configuration.choice'),
        ),
    ]
