# Generated by Django 5.1.12 on 2025-11-01 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_choice_category'),
        ('maintenance', '0004_alter_maintenancerecord_items_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tyre',
            name='tyre_positio_d5bd16_idx',
        ),
        migrations.RenameIndex(
            model_name='tyre',
            new_name='tyre_Brand_i_927c0a_idx',
            old_name='tyre_Brand_ff2f0b_idx',
        ),
        migrations.RenameIndex(
            model_name='tyre',
            new_name='tyre_Size_id_e57a38_idx',
            old_name='tyre_Size_7ba51b_idx',
        ),
        migrations.RemoveField(
            model_name='tyre',
            name='position',
        ),
        migrations.RemoveField(
            model_name='tyre',
            name='position_choice',
        ),
        migrations.AlterField(
            model_name='tyre',
            name='Brand',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'TYRE_BRAND'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyre_brand', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='Model',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'TYRE_MODEL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyre_model', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='Purchase_Type',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'TYRE_PURCHASE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyre_purchase_type', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='Size',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'TYRE_SIZE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyre_size', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='Type',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'TYRE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyre_type', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='tube_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'TYRE_TUBE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyre_tube_type', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='tyretransaction',
            name='position',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'TYRE_POSITION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyre_position', to='configuration.choice'),
        ),
    ]
