# Generated by Django 5.1.12 on 2025-11-01 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_remove_tyre_tyre_positio_d5bd16_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tyre',
            old_name='Type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='tyre',
            name='brand_choice',
        ),
        migrations.RemoveField(
            model_name='tyre',
            name='tube_type_choice',
        ),
        migrations.RemoveField(
            model_name='tyre',
            name='tyre_type_choice',
        ),
    ]
