# Generated by Django 5.1.12 on 2025-11-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_alter_choice_category'),
        ('maintenance', '0006_rename_type_tyre_type_remove_tyre_brand_choice_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tyre',
            options={'ordering': ['brand', 'model', 'size']},
        ),
        migrations.RemoveIndex(
            model_name='tyre',
            name='tyre_Brand_i_927c0a_idx',
        ),
        migrations.RemoveIndex(
            model_name='tyre',
            name='tyre_Size_id_e57a38_idx',
        ),
        migrations.RemoveIndex(
            model_name='tyre',
            name='tyre_Purchas_a3ec96_idx',
        ),
        migrations.RenameField(
            model_name='tyre',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='tyre',
            old_name='Model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='tyre',
            old_name='Purchase_by',
            new_name='purchase_by',
        ),
        migrations.RenameField(
            model_name='tyre',
            old_name='Purchase_Date',
            new_name='purchase_date',
        ),
        migrations.RenameField(
            model_name='tyre',
            old_name='Purchase_Type',
            new_name='purchase_type',
        ),
        migrations.RenameField(
            model_name='tyre',
            old_name='Size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='tyre',
            old_name='TyreNo',
            new_name='tyreNo',
        ),
        migrations.RenameField(
            model_name='tyre',
            old_name='Tyre_document',
            new_name='tyre_document',
        ),
        migrations.AddIndex(
            model_name='tyre',
            index=models.Index(fields=['brand', 'model'], name='tyre_brand_i_843bb5_idx'),
        ),
        migrations.AddIndex(
            model_name='tyre',
            index=models.Index(fields=['size'], name='tyre_size_id_e9f438_idx'),
        ),
        migrations.AddIndex(
            model_name='tyre',
            index=models.Index(fields=['purchase_date'], name='tyre_purchas_f1eeb5_idx'),
        ),
    ]
