# Generated by Django 5.1.12 on 2025-11-04 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('maintenance', '0007_alter_tyre_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label': 'entity', 'model__in': ['driver', 'organization']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
