# Generated by Django 5.1.12 on 2025-11-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_convert_tyretransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyre',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase amount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='purchase_by',
            field=models.CharField(blank=True, help_text='Purchased by (person/organization)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tyre',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Date of tyre purchase', null=True),
        ),
    ]
