# Generated by Django 5.1.12 on 2025-09-06 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('entity', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='broker',
            name='gender',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'GENDER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_gender_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='broker',
            name='route',
            field=models.ForeignKey(blank=True, help_text='Primary route of operation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_routes', to='configuration.route'),
        ),
        migrations.AddField(
            model_name='broker',
            name='title',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'TITLE_CHOICES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_title_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='broker',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='broker',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, help_text='Preferred vehicle types for brokerage', limit_choices_to={'category': 'BROKER_VEHICLE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BROKER_VEHICLE_TYPE', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='driver',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'GENDER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_gender_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='driver',
            name='title',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'TITLE_CHOICES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_title_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='driver',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to='users.customuser'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['organization_type'], name='organizatio_organiz_b4644e_idx'),
        ),
        migrations.AddField(
            model_name='broker',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this broker belongs to (tenant)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.organization'),
        ),
        migrations.AddField(
            model_name='owner',
            name='gender',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'GENDER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_gender_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='owner',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this owner belongs to (tenant)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.organization'),
        ),
        migrations.AddField(
            model_name='owner',
            name='route',
            field=models.ForeignKey(blank=True, help_text='Primary route of operation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_routes', to='configuration.route'),
        ),
        migrations.AddField(
            model_name='owner',
            name='state_registered',
            field=models.ForeignKey(blank=True, help_text='State where owner is registered', limit_choices_to={'category': 'STATE_CHOICES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_state_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='owner',
            name='title',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'TITLE_CHOICES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_title_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='driver',
            name='owners',
            field=models.ForeignKey(help_text='Owner this driver works for (REQUIRED - industry standard)', on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='entity.owner'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='gender',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'GENDER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_gender_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this transporter belongs to (tenant)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.organization'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='title',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'TITLE_CHOICES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_title_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.ForeignKey(blank=True, help_text='Body type from predefined choices', limit_choices_to={'category': 'BODY_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_body_type_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand_name',
            field=models.ForeignKey(blank=True, help_text='Brand from predefined choices', limit_choices_to={'category': 'BRAND_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_brand_choice_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_type',
            field=models.ForeignKey(blank=True, help_text='Engine type from predefined choices', limit_choices_to={'category': 'ENGINE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_engine_type_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.ForeignKey(blank=True, help_text='Fuel type from predefined choices', limit_choices_to={'category': 'FUEL_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_fuel_choice_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='load_capacity_tons',
            field=models.ForeignKey(blank=True, help_text='Gross Vehicle Weight (e.g., 28T, 16.2T)', limit_choices_to={'category': 'CAPACITY_TONS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_capacity_type_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_name',
            field=models.ForeignKey(blank=True, help_text='Model from predefined choices', limit_choices_to={'category': 'MODEL_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_model_choice_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_owner', to='entity.owner'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='state_registered',
            field=models.ForeignKey(blank=True, help_text='State where vehicle is registered', limit_choices_to={'category': 'STATE_CHOICES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vechile_state_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='truck_specification',
            field=models.ForeignKey(blank=True, help_text='Truck specification from predefined choices', limit_choices_to={'category': 'TRUCK_SPECIFICATION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_specification_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='truck_type',
            field=models.ForeignKey(blank=True, help_text='Truck type from predefined choices', limit_choices_to={'category': 'TRUCK_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_truck_type_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='wheel_count',
            field=models.ForeignKey(blank=True, help_text='Number of wheels (e.g., 6, 10, 12)', limit_choices_to={'category': 'WHEELS_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_wheels_type_set', to='configuration.choice'),
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['organization'], name='broker_organiz_78ac25_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['organization'], name='owner_organiz_4d8966_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['state_registered'], name='owner_state_r_731a27_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['owners'], name='driver_owners__5f8015_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['license_number'], name='driver_license_20b330_idx'),
        ),
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.UniqueConstraint(condition=models.Q(('license_number__isnull', False)), fields=('license_number',), name='unique_driver_license'),
        ),
        migrations.AddIndex(
            model_name='transporter',
            index=models.Index(fields=['organization'], name='transporter_organiz_80b566_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['owner'], name='vehicle_owner_i_77c561_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['registration_number'], name='vehicle_registr_8a1aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['chassis_number'], name='vehicle_chassis_847db2_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active'], name='vehicle_is_acti_0a5f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['brand_name', 'model_name'], name='vehicle_brand_n_08553e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['truck_type'], name='vehicle_truck_t_aa25d1_idx'),
        ),
    ]
