# Generated by Django 5.1.12 on 2025-11-02 02:50

import django.db.models.deletion
import entity.models
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_alter_choice_category'),
        ('entity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='pan_document',
            field=models.FileField(blank=True, null=True, upload_to=utils.validators.user_document_upload_path, validators=[utils.validators.document_file_validator]),
        ),
        migrations.AddField(
            model_name='organization',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[utils.validators.pan_validator]),
        ),
        migrations.AddField(
            model_name='organization',
            name='route',
            field=models.ForeignKey(blank=True, help_text='Primary route of operation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_routes', to='configuration.route'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tds_declaration',
            field=models.FileField(blank=True, null=True, upload_to=utils.validators.user_document_upload_path, validators=[utils.validators.document_file_validator]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('BROKER', 'Broker'), ('TRANSPORTER', 'Transporter'), ('CONSIGNOR-AND-CONSIGNEE', 'Consignor & Consignee'), ('OWNER', 'Owner')], help_text='Type of organization', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(help_text='Vehicle registration number (e.g., MH12AB123)', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('REG_CERT', 'Registration Certificate'), ('TAX', 'Tax'), ('NATIONAL_PERMIT', 'National Permit'), ('STATE_PERMIT', 'State Permit'), ('POLLUTION', 'Pollution'), ('INSURANCE', 'Insurance'), ('VLTD_CERT', 'VLTD Certificate'), ('SPEED_GOVERNOR', 'Speed Governor Certificate')], db_index=True, max_length=32)),
                ('file', models.FileField(upload_to=entity.models.vehicle_document_path)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='entity.vehicle')),
            ],
            options={
                'db_table': 'vehicle_document',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['vehicle', 'doc_type'], name='vehicle_doc_vehicle_b89ac1_idx'), models.Index(fields=['uploaded_at'], name='vehicle_doc_uploade_ba3fed_idx')],
            },
        ),
    ]
