# Generated by Django 5.1.12 on 2025-11-02 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_organization_pan_document_organization_pan_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='pan_document',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='pan_document',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='pan_number',
        ),
    ]
