# Generated by Django 5.1.12 on 2025-11-02 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_remove_broker_pan_document_remove_broker_pan_number_and_more'),
    ]

    operations = [
    ]
