# Generated by Django 5.1.12 on 2025-11-02 03:02

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_cleanup_vehicle_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='pan_document',
            field=models.FileField(blank=True, null=True, upload_to=utils.validators.user_document_upload_path, validators=[utils.validators.document_file_validator]),
        ),
        migrations.AddField(
            model_name='broker',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[utils.validators.pan_validator]),
        ),
        migrations.AddField(
            model_name='driver',
            name='pan_document',
            field=models.FileField(blank=True, null=True, upload_to=utils.validators.user_document_upload_path, validators=[utils.validators.document_file_validator]),
        ),
        migrations.AddField(
            model_name='driver',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[utils.validators.pan_validator]),
        ),
    ]
