# Generated by Django 5.1.12 on 2025-11-02 21:11

import django.db.models.deletion
import entity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_cleanup_vehicle_columns_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('LICENSE', 'Driving License'), ('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('MEDICAL', 'Medical/Health'), ('POLICE', 'Police Verification'), ('OTHER', 'Other')], db_index=True, max_length=24)),
                ('file', models.FileField(upload_to=entity.models.driver_document_path)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='entity.driver')),
            ],
            options={
                'db_table': 'driver_document',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['driver', 'doc_type'], name='driver_docu_driver__9ca341_idx'), models.Index(fields=['uploaded_at'], name='driver_docu_uploade_958f9e_idx')],
            },
        ),
    ]
