# Generated by Django 5.1.12 on 2025-11-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0008_driverdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverdocument',
            name='notes',
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='doc_no',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
