# Generated by Django 5.1.12 on 2025-11-02 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0009_remove_driverdocument_notes_driverdocument_doc_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='aadhaar',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='aadhaar_document',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='pan_document',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='updated_by',
        ),
    ]
