# Generated by Django 5.1.12 on 2025-11-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_alter_choice_category'),
        ('entity', '0011_remove_owner_related_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='driver',
            name='driver_owners__5f8015_idx',
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['owner'], name='driver_owner_i_7cc4b7_idx'),
        ),
    ]
