# Generated by Django 5.1.12 on 2025-11-04 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_alter_choice_category'),
        ('entity', '0012_remove_driver_driver_owners__5f8015_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Select location from dropdown', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='configuration.location'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_number',
            field=models.CharField(default=1, editable=False, help_text='Auto-generated organization number in format ORG-00001', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
