# Generated by Django 5.1.12 on 2025-11-05 01:53

import django.db.models.deletion
import entity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_convert_bankingdetail_account_type'),
        ('entity', '0013_organization_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=entity.models.organization_document_path)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('doc_no', models.CharField(blank=True, max_length=60, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organization_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='driverdocument',
            new_name='driver_docu_driver__d496a4_idx',
            old_name='driver_docu_driver__9ca341_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organization_type_idx',
            old_name='organizatio_organiz_b4644e_idx',
        ),
        migrations.RenameIndex(
            model_name='vehicledocument',
            new_name='vehicle_doc_vehicle_f2f33c_idx',
            old_name='vehicle_doc_vehicle_b89ac1_idx',
        ),
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'PERSON_GENDER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_gender_set', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='owner',
            field=models.ForeignKey(help_text='Owner organization this driver works for (REQUIRED - industry standard)', limit_choices_to={'organization_type__internal_value': 'OWNER'}, on_delete=django.db.models.deletion.PROTECT, related_name='drivers', to='entity.organization'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='title',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'PERSON_TITLE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_title_set', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='doc_type',
            field=models.ForeignKey(limit_choices_to={'category': 'DRIVER_DOCUMENT_TYPE'}, on_delete=django.db.models.deletion.PROTECT, related_name='driver_documents', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.ForeignKey(blank=True, help_text='Type of organization', limit_choices_to={'category': 'ORGANIZATION_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_type_members', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.ForeignKey(blank=True, help_text='Body type from predefined choices', limit_choices_to={'category': 'VEHICLE_BODY_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_body_type_set', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand_name',
            field=models.ForeignKey(blank=True, help_text='Brand from predefined choices', limit_choices_to={'category': 'VEHICLE_BRAND'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_brand_choice_set', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_type',
            field=models.ForeignKey(blank=True, help_text='Engine type from predefined choices', limit_choices_to={'category': 'VEHICLE_ENGINE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_engine_type_set', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.ForeignKey(blank=True, help_text='Fuel type from predefined choices', limit_choices_to={'category': 'VEHICLE_FUEL_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_fuel_choice_set', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='load_capacity_tons',
            field=models.ForeignKey(blank=True, help_text='Gross Vehicle Weight (e.g., 28T, 16.2T)', limit_choices_to={'category': 'VEHICLE_CAPACITY_TONNAGE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_capacity_type_set', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model_name',
            field=models.ForeignKey(blank=True, help_text='Model from predefined choices', limit_choices_to={'category': 'VEHICLE_MODEL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_model_choice_set', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner organization responsible for this vehicle', limit_choices_to={'organization_type__internal_value': 'OWNER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='entity.organization'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='state_registered',
            field=models.ForeignKey(blank=True, help_text='State where vehicle is registered', limit_choices_to={'category': 'LOCATION_STATE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vechile_state_set', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='truck_specification',
            field=models.ForeignKey(blank=True, help_text='Truck specification from predefined choices', limit_choices_to={'category': 'VEHICLE_SPECIFICATION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_specification_set', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='truck_type',
            field=models.ForeignKey(blank=True, help_text='Truck type from predefined choices', limit_choices_to={'category': 'VEHICLE_TRUCK_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_truck_type_set', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='wheel_count',
            field=models.ForeignKey(blank=True, help_text='Number of wheels (e.g., 6, 10, 12)', limit_choices_to={'category': 'VEHICLE_WHEEL_CONFIGURATION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_wheels_type_set', to='configuration.choice'),
        ),
        migrations.AlterField(
            model_name='vehicledocument',
            name='doc_type',
            field=models.ForeignKey(limit_choices_to={'category': 'VEHICLE_DOCUMENT_TYPE'}, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_documents', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='organizationdocument',
            name='doc_type',
            field=models.ForeignKey(limit_choices_to={'category': 'ORGANIZATION_DOCUMENT_TYPE'}, on_delete=django.db.models.deletion.PROTECT, related_name='organization_documents', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='organizationdocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='entity.organization'),
        ),
        migrations.AddIndex(
            model_name='organizationdocument',
            index=models.Index(fields=['organization', 'doc_type'], name='organizatio_organiz_b16e11_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationdocument',
            index=models.Index(fields=['uploaded_at'], name='organizatio_uploade_5db79f_idx'),
        ),
    ]
