# Generated by Django 5.1.12 on 2025-12-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0014_organizationdocument_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['first_name', 'middle_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['organization_name']},
        ),
    ]
