# Generated by Django 5.1.12 on 2025-12-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0015_alter_driver_options_alter_organization_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether Driver is active or not'),
        ),
    ]
