# Generated by Django 5.1.12 on 2025-12-31 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0016_driver_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Diesel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, help_text='Transfer description and purpose', null=True)),
                ('price_per_ltr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('full_km', models.DecimalField(decimal_places=2, help_text='Odometer reading', max_digits=12)),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rs_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('ONLINE', 'Online'), ('CASH', 'Cash')], max_length=10)),
                ('driver_taken_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('upload_doc', models.FileField(blank=True, null=True, upload_to='diesel_slips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diesel_entries', to='entity.vehicle')),
            ],
        ),
    ]
