# Generated by Django 5.1.12 on 2025-12-31 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0017_alter_organization_notes_diesel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diesel',
        ),
    ]
