# Generated by Django 5.1.12 on 2025-09-06 23:45

import django.db.models.deletion
import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsignmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('planned_dispatch_date', models.DateField(blank=True, help_text='Planned dispatch date for this group', null=True)),
                ('actual_dispatch_date', models.DateField(blank=True, help_text='Actual dispatch date', null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Total weight of all consignments in this group', max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount for all consignments in this group', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'consignment_group',
            },
        ),
        migrations.CreateModel(
            name='DriverAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, help_text='Purpose of advance (e.g. fuel, lodging)', max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_settled', models.BooleanField(default=False)),
                ('carried_forward', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'driver_advance',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('planned_departure', models.DateTimeField(blank=True, help_text='Planned departure time', null=True)),
                ('actual_departure', models.DateTimeField(blank=True, help_text='Actual departure time', null=True)),
                ('planned_arrival', models.DateTimeField(blank=True, help_text='Planned arrival time', null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, help_text='Actual arrival time', null=True)),
                ('odometer_start', models.DecimalField(blank=True, decimal_places=2, help_text='Starting odometer reading', max_digits=10, null=True)),
                ('odometer_end', models.DecimalField(blank=True, decimal_places=2, help_text='Ending odometer reading', max_digits=10, null=True)),
                ('total_distance', models.DecimalField(blank=True, decimal_places=2, help_text='Total distance covered in km', max_digits=10, null=True)),
                ('advance_received', models.DecimalField(decimal_places=2, default=0, help_text='Total advance received for this shipment', max_digits=15)),
                ('total_freight_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total freight amount for all consignments in this shipment', max_digits=15, null=True)),
                ('notes', models.CharField(blank=True, help_text='General notes about the shipment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
        migrations.CreateModel(
            name='ShipmentExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('shipment_expense_document', models.FileField(blank=True, null=True, upload_to=utils.validators.user_document_upload_path, validators=[utils.validators.document_file_validator])),
            ],
            options={
                'db_table': 'shipmentexpense',
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_document', models.FileField(blank=True, null=True, upload_to=utils.validators.user_document_upload_path, validators=[utils.validators.document_file_validator])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(blank=True, help_text='User who updated the status', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this status change', null=True)),
            ],
            options={
                'db_table': 'shipmentstatus',
            },
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('weight', models.DecimalField(decimal_places=3, help_text='Weight in tonnes/kg', max_digits=10)),
                ('volume', models.DecimalField(blank=True, decimal_places=3, help_text='Volume in cubic meters', max_digits=10, null=True)),
                ('number_of_packages', models.PositiveIntegerField(blank=True, help_text='Number of packages/pieces', null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rate per kg/tonne based on freight mode', max_digits=10, null=True)),
                ('total_freight', models.DecimalField(decimal_places=2, help_text='Total freight amount for this consignment', max_digits=15)),
                ('schedule_date', models.DateField(blank=True, help_text='Scheduled pickup date', null=True, validators=[utils.validators.future_date_validator])),
                ('scheduled_pickup_time', models.TimeField(blank=True, help_text='Scheduled pickup time', null=True)),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Expected delivery date', null=True)),
                ('expected_delivery_time', models.TimeField(blank=True, help_text='Expected delivery time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consignee', models.ForeignKey(blank=True, help_text='Organization receiving the goods', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consignee_consignments', to='entity.organization')),
                ('consignor', models.ForeignKey(blank=True, help_text='Organization sending the goods', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consignor_consignments', to='entity.organization')),
            ],
            options={
                'db_table': 'consignment',
            },
        ),
    ]
