# Generated by Django 5.1.12 on 2025-09-06 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('entity', '0002_initial'),
        ('operations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consignments', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='freight_mode',
            field=models.ForeignKey(blank=True, help_text='Freight calculation mode (Rate, Fixed, etc.)', limit_choices_to={'category': 'FREIGHT_MODE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignment_freight_mode_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='material_type',
            field=models.ForeignKey(blank=True, default=1, help_text='Specific material type (e.g., Steel, Electronics, Food Items)', limit_choices_to={'category': 'MATERIAL_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignment_material_type_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='packaging_type',
            field=models.ForeignKey(blank=True, help_text='Type of packaging (boxes, pallets, loose, etc.)', limit_choices_to={'category': 'PACKAGING_TYPES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignment_packaging_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, help_text='Preferred vehicle types for Consignment', limit_choices_to={'category': 'BROKER_VEHICLE_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Consignment_VEHICLE_TYPE', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='weight_unit',
            field=models.ForeignKey(blank=True, default=1, help_text='Unit of weight measurement', limit_choices_to={'category': 'WEIGHT_UNITS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignment_weight_unit_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='consignmentgroup',
            name='consignments',
            field=models.ManyToManyField(blank=True, to='operations.consignment'),
        ),
        migrations.AddField(
            model_name='consignmentgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consignment_groups', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='driveradvance',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entity.driver'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='actual_route',
            field=models.ForeignKey(blank=True, help_text='Actual route taken', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_route_actual_set', to='configuration.route'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='broker',
            field=models.ForeignKey(blank=True, help_text='Broker facilitating the shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_broker', to='entity.broker'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='co_driver',
            field=models.ForeignKey(blank=True, help_text='Co-driver if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_driver_shipments', to='entity.driver'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='consignment_group',
            field=models.OneToOneField(blank=True, help_text='Consignment group assigned to this shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment', to='operations.consignmentgroup'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Primary driver assigned', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to='entity.driver'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='planned_route',
            field=models.ForeignKey(blank=True, help_text='Planned route taken', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_route_planned_set', to='configuration.route'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='transporter',
            field=models.ForeignKey(blank=True, help_text='Transporter handling the shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_transporter', to='entity.transporter'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Vehicle assigned for this shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='entity.vehicle'),
        ),
        migrations.AddField(
            model_name='driveradvance',
            name='shipment',
            field=models.ForeignKey(blank=True, help_text='Shipment this advance is for (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.shipment'),
        ),
        migrations.AddField(
            model_name='shipmentexpense',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'app_label': 'entity', 'model__in': ['driver', 'owner']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='shipmentexpense',
            name='expense_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'EXPENSE_TYPES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_expense_set', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='shipmentexpense',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='operations.shipment'),
        ),
        migrations.AddField(
            model_name='shipmentstatus',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='operations.shipment'),
        ),
        migrations.AddField(
            model_name='shipmentstatus',
            name='shipment_doc_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'SHIPMENT_DOC_TYPE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_doc_type', to='configuration.choice'),
        ),
        migrations.AddField(
            model_name='shipmentstatus',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'STATUS_CHOICES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_status_log_set', to='configuration.choice'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['consignor'], name='consignment_consign_e6bec8_idx'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['consignee'], name='consignment_consign_342860_idx'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['schedule_date'], name='consignment_schedul_e120a7_idx'),
        ),
        migrations.AddIndex(
            model_name='consignment',
            index=models.Index(fields=['created_at'], name='consignment_created_e7c4e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='consignment',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='positive_weight'),
        ),
        migrations.AddConstraint(
            model_name='consignment',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_packages__gt', 0), ('number_of_packages__isnull', True), _connector='OR'), name='positive_package_count'),
        ),
        migrations.AddIndex(
            model_name='consignmentgroup',
            index=models.Index(fields=['planned_dispatch_date'], name='consignment_planned_45eeda_idx'),
        ),
        migrations.AddIndex(
            model_name='consignmentgroup',
            index=models.Index(fields=['created_at'], name='consignment_created_580bfd_idx'),
        ),
        migrations.AddConstraint(
            model_name='consignmentgroup',
            constraint=models.CheckConstraint(condition=models.Q(('total_weight__gte', 0), ('total_weight__isnull', True), _connector='OR'), name='non_negative_total_weight'),
        ),
        migrations.AddConstraint(
            model_name='consignmentgroup',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0), ('total_amount__isnull', True), _connector='OR'), name='non_negative_total_amount'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['consignment_group'], name='shipment_consign_bed95c_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['vehicle'], name='shipment_vehicle_163abf_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['driver'], name='shipment_driver__61419f_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['transporter'], name='shipment_transpo_1b5cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['actual_departure'], name='shipment_actual__7940f8_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['planned_departure'], name='shipment_planned_614083_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['created_at'], name='shipment_created_b5c50a_idx'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(condition=models.Q(('advance_received__gte', 0)), name='non_negative_advance'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(condition=models.Q(('total_distance__gte', 0), ('total_distance__isnull', True), _connector='OR'), name='non_negative_distance'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(condition=models.Q(('odometer_end__gte', models.F('odometer_start')), ('odometer_end__isnull', True), ('odometer_start__isnull', True), _connector='OR'), name='valid_odometer_reading'),
        ),
        migrations.AddIndex(
            model_name='driveradvance',
            index=models.Index(fields=['driver'], name='driver_adva_driver__98ac77_idx'),
        ),
        migrations.AddIndex(
            model_name='driveradvance',
            index=models.Index(fields=['date'], name='driver_adva_date_c2b426_idx'),
        ),
        migrations.AddIndex(
            model_name='driveradvance',
            index=models.Index(fields=['shipment', 'driver'], name='driver_adva_shipmen_c24e78_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentexpense',
            index=models.Index(fields=['shipment'], name='shipmentexp_shipmen_a4ebac_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentexpense',
            index=models.Index(fields=['expense_date'], name='shipmentexp_expense_5343c5_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentexpense',
            index=models.Index(fields=['shipment', 'expense_date'], name='shipmentexp_shipmen_2db4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentexpense',
            index=models.Index(fields=['expense_type', 'expense_date'], name='shipmentexp_expense_3ee6b1_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentstatus',
            index=models.Index(fields=['shipment'], name='shipmentsta_shipmen_b3acd5_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentstatus',
            index=models.Index(fields=['timestamp'], name='shipmentsta_timesta_7bc5b7_idx'),
        ),
        migrations.AddIndex(
            model_name='shipmentstatus',
            index=models.Index(fields=['status'], name='shipmentsta_status__4c24cd_idx'),
        ),
    ]
