# Generated by Django 5.1.12 on 2025-10-22 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('operations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveradvance',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'entity'), ('model', 'owner')), models.Q(('app_label', 'operation'), ('model', 'shipment')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='driveradvance',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
