# Generated by Django 5.1.12 on 2025-11-01 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_choice_category'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('entity', '0002_initial'),
        ('operations', '0003_driveradvance_content_type_driveradvance_object_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shipment',
            name='non_negative_advance',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='advance_received',
            new_name='freight_advance',
        ),
        migrations.AlterField(
            model_name='driveradvance',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'entity'), ('model', 'owner')), models.Q(('app_label', 'operations'), ('model', 'shipment')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddConstraint(
            model_name='shipment',
            constraint=models.CheckConstraint(condition=models.Q(('freight_advance__gte', 0)), name='non_negative_advance'),
        ),
    ]
