# Generated by Django 5.1.12 on 2025-12-22 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_update_choice_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consignmentgroup',
            options={'ordering': ['group_id']},
        ),
    ]
