# Generated by Django 5.1.12 on 2025-12-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_alter_consignmentgroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveradvance',
            name='description',
            field=models.CharField(blank=True, help_text='Purpose of advance (e.g. fuel, lodging)', max_length=1000),
        ),
        migrations.AlterField(
            model_name='shipmentexpense',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
