# Generated by Django 5.1.12 on 2026-01-07 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_convert_bankingdetail_account_type'),
        ('operations', '0010_alter_consignment_schedule_date_diesel'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='from_location',
            field=models.ForeignKey(blank=True, help_text='Select location from dropdown', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignment_from_location', to='configuration.location'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='to_location',
            field=models.ForeignKey(blank=True, help_text='Select location from dropdown', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignment_location_to', to='configuration.location'),
        ),
    ]
