# Generated by Django 5.1.12 on 2026-01-08 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_convert_bankingdetail_account_type'),
        ('operations', '0011_consignment_from_location_consignment_to_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='diesel',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Select location from dropdown', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diesel_location', to='configuration.location'),
        ),
    ]
