# Generated by Django 5.1.12 on 2026-03-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_diesel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignment',
            name='e_way_bill',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='E-Way Bill'),
        ),
        migrations.AddField(
            model_name='consignment',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Invoice No'),
        ),
    ]
