# Generated by Django 5.1.12 on 2026-04-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0014_remove_consignment_e_way_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='lr_no',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='LR No'),
        ),
    ]
