# Generated by Django 5.1.12 on 2026-04-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_convert_bankingdetail_account_type'),
        ('operations', '0015_shipment_lr_no'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shipmentstatus',
            name='shipmentsta_timesta_7bc5b7_idx',
        ),
        migrations.RemoveField(
            model_name='shipmentstatus',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='shipmentstatus',
            name='effective_date',
            field=models.DateTimeField(blank=True, help_text='Planned arrival time', null=True),
        ),
        migrations.AddIndex(
            model_name='shipmentstatus',
            index=models.Index(fields=['effective_date'], name='shipmentsta_effecti_07b6f9_idx'),
        ),
    ]
