# Generated by Django 5.1.12 on 2026-04-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0016_remove_shipmentstatus_shipmentsta_timesta_7bc5b7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentstatus',
            name='effective_date',
            field=models.DateTimeField(blank=True, help_text='effective_date', null=True),
        ),
    ]
