# Generated by Django 5.1.12 on 2026-04-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_alter_shipmentstatus_effective_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diesel',
            name='full_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Odometer reading', max_digits=12, null=True),
        ),
    ]
