# Generated by Django 5.1.12 on 2026-04-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0018_alter_diesel_full_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diesel',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
